In [45]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
numpy.random.seed(7)

In [2]:
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8] #pierwsze 7 kolumn
Y = dataset[:,8] # 8 kolumna

In [3]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [5]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [15]:
train = pd.read_csv("pima-indians-diabetes.csv", delimiter=",", header=None)

In [16]:
train

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
5     5  116  74   0    0  25.6  0.201  30  0
6     3   78  50  32   88  31.0  0.248  26  1
7    10  115   0   0    0  35.3  0.134  29  0
8     2  197  70  45  543  30.5  0.158  53  1
9     8  125  96   0    0   0.0  0.232  54  1
10    4  110  92   0    0  37.6  0.191  30  0
11   10  168  74   0    0  38.0  0.537  34  1
12   10  139  80   0    0  27.1  1.441  57  0
13    1  189  60  23  846  30.1  0.398  59  1
14    5  166  72  19  175  25.8  0.587  51  1
15    7  100   0   0    0  30.0  0.484  32  1
16    0  118  84  47  230  45.8  0.551  31  1
17    7  107  74   0    0  29.6  0.254  31  1
18    1  103  30  38   83  43.3  0.183  33  0
19    1  115  70  30   96  34.6  0.529  32  1
20    3  126  88  41  235  39.3  0.704  27  0
21    8   99  84   0    0  35.4  0.388  50  0
22    7  196  90   0    0  39.8  0.451  41  1
23    9  119  80  35    0  29.0  0.263  29  1
24   11  143  94  33  146  36.6  0.254  51  1
25   10  125  70  26  115  31.1  0.205  41  1
26    7  147  76   0    0  39.4  0.257  43  1
27    1   97  66  15  140  23.2  0.487  22  0
28   13  145  82  19  110  22.2  0.245  57  0
29    5  117  92   0    0  34.1  0.337  38  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
738   2   99  60  17  160  36.6  0.453  21  0
739   1  102  74   0    0  39.5  0.293  42  1
740  11  120  80  37  150  42.3  0.785  48  1
741   3  102  44  20   94  30.8  0.400  26  0
742   1  109  58  18  116  28.5  0.219  22  0
743   9  140  94   0    0  32.7  0.734  45  1
744  13  153  88  37  140  40.6  1.174  39  0
745  12  100  84  33  105  30.0  0.488  46  0
746   1  147  94  41    0  49.3  0.358  27  1
747   1   81  74  41   57  46.3  1.096  32  0
748   3  187  70  22  200  36.4  0.408  36  1
749   6  162  62   0    0  24.3  0.178  50  1
750   4  136  70   0    0  31.2  1.182  22  1
751   1  121  78  39   74  39.0  0.261  28  0
752   3  108  62  24    0  26.0  0.223  25  0
753   0  181  88  44  510  43.3  0.222  26  1
754   8  154  78  32    0  32.4  0.443  45  1
755   1  128  88  39  110  36.5  1.057  37  1
756   7  137  90  41    0  32.0  0.391  39  0
757   0  123  72   0    0  36.3  0.258  52  1
758   1  106  76   0    0  37.5  0.197  26  0
759   6  190  92   0    0  35.5  0.278  66  1
760   2   88  58  26   16  28.4  0.766  22  0
761   9  170  74  31    0  44.0  0.403  43  1
762   9   89  62   0    0  22.5  0.142  33  0
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [18]:
X_train = (train.iloc[:,1:].values).astype('float32') # all pixel values
#Y_train = train.iloc[:,0].values.astype('int32') # only labels
#X_test = test.values.astype('int32')

In [21]:
X_train=train.iloc[:,0:8]

In [22]:
X_train

0    1   2   3    4     5      6   7
0     6  148  72  35    0  33.6  0.627  50
1     1   85  66  29    0  26.6  0.351  31
2     8  183  64   0    0  23.3  0.672  32
3     1   89  66  23   94  28.1  0.167  21
4     0  137  40  35  168  43.1  2.288  33
5     5  116  74   0    0  25.6  0.201  30
6     3   78  50  32   88  31.0  0.248  26
7    10  115   0   0    0  35.3  0.134  29
8     2  197  70  45  543  30.5  0.158  53
9     8  125  96   0    0   0.0  0.232  54
10    4  110  92   0    0  37.6  0.191  30
11   10  168  74   0    0  38.0  0.537  34
12   10  139  80   0    0  27.1  1.441  57
13    1  189  60  23  846  30.1  0.398  59
14    5  166  72  19  175  25.8  0.587  51
15    7  100   0   0    0  30.0  0.484  32
16    0  118  84  47  230  45.8  0.551  31
17    7  107  74   0    0  29.6  0.254  31
18    1  103  30  38   83  43.3  0.183  33
19    1  115  70  30   96  34.6  0.529  32
20    3  126  88  41  235  39.3  0.704  27
21    8   99  84   0    0  35.4  0.388  50
22    7  196  90   0    0  39.8  0.451  41
23    9  119  80  35    0  29.0  0.263  29
24   11  143  94  33  146  36.6  0.254  51
25   10  125  70  26  115  31.1  0.205  41
26    7  147  76   0    0  39.4  0.257  43
27    1   97  66  15  140  23.2  0.487  22
28   13  145  82  19  110  22.2  0.245  57
29    5  117  92   0    0  34.1  0.337  38
..   ..  ...  ..  ..  ...   ...    ...  ..
738   2   99  60  17  160  36.6  0.453  21
739   1  102  74   0    0  39.5  0.293  42
740  11  120  80  37  150  42.3  0.785  48
741   3  102  44  20   94  30.8  0.400  26
742   1  109  58  18  116  28.5  0.219  22
743   9  140  94   0    0  32.7  0.734  45
744  13  153  88  37  140  40.6  1.174  39
745  12  100  84  33  105  30.0  0.488  46
746   1  147  94  41    0  49.3  0.358  27
747   1   81  74  41   57  46.3  1.096  32
748   3  187  70  22  200  36.4  0.408  36
749   6  162  62   0    0  24.3  0.178  50
750   4  136  70   0    0  31.2  1.182  22
751   1  121  78  39   74  39.0  0.261  28
752   3  108  62  24    0  26.0  0.223  25
753   0  181  88  44  510  43.3  0.222  26
754   8  154  78  32    0  32.4  0.443  45
755   1  128  88  39  110  36.5  1.057  37
756   7  137  90  41    0  32.0  0.391  39
757   0  123  72   0    0  36.3  0.258  52
758   1  106  76   0    0  37.5  0.197  26
759   6  190  92   0    0  35.5  0.278  66
760   2   88  58  26   16  28.4  0.766  22
761   9  170  74  31    0  44.0  0.403  43
762   9   89  62   0    0  22.5  0.142  33
763  10  101  76  48  180  32.9  0.171  63
764   2  122  70  27    0  36.8  0.340  27
765   5  121  72  23  112  26.2  0.245  30
766   1  126  60   0    0  30.1  0.349  47
767   1   93  70  31    0  30.4  0.315  23

[768 rows x 8 columns]

In [23]:
X_test=train.iloc[:,8]

In [24]:
X_test

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: 8, Length: 768, dtype: int64

In [31]:
X_train.shape

(768, 8)

In [33]:
X_test.shape

(768,)

In [25]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [26]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [28]:
# Fit the model
model.fit(X_train, X_test, epochs=50, batch_size=20)

Epoch 1/50
768/768 [==============================] - 0s 52us/step - loss: 0.4643 - acc: 0.7917
Epoch 2/50
768/768 [==============================] - 0s 46us/step - loss: 0.4586 - acc: 0.8008
Epoch 3/50
768/768 [==============================] - 0s 52us/step - loss: 0.4569 - acc: 0.7917
Epoch 4/50
768/768 [==============================] - 0s 42us/step - loss: 0.4606 - acc: 0.7891
Epoch 5/50
768/768 [==============================] - 0s 46us/step - loss: 0.4549 - acc: 0.7930
Epoch 6/50
768/768 [==============================] - 0s 48us/step - loss: 0.4568 - acc: 0.7943
Epoch 7/50
768/768 [==============================] - 0s 46us/step - loss: 0.4539 - acc: 0.7917
Epoch 8/50
768/768 [==============================] - 0s 47us/step - loss: 0.4517 - acc: 0.7943
Epoch 9/50
768/768 [==============================] - 0s 46us/step - loss: 0.4559 - acc: 0.7878
Epoch 10/50
768/768 [==============================] - 0s 46us/step - loss: 0.4590 - acc: 0.7891
Epoch 11/50
768/768 [==================

In [34]:
scores = model.evaluate(X_train, X_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

768/768 [==============================] - 0s 15us/step

acc: 78.65%


In [38]:
# calculate predictions
predictions = model.predict(X_train)
predictions

array([[7.71504879e-01],
       [7.90440887e-02],
       [7.23617852e-01],
       [1.07418820e-01],
       [7.27585971e-01],
       [1.25065655e-01],
       [2.31706768e-01],
       [3.14298600e-01],
       [9.15429831e-01],
       [4.81606349e-02],
       [7.34690055e-02],
       [7.78331220e-01],
       [1.93492949e-01],
       [7.57816970e-01],
       [7.53648996e-01],
       [1.57541975e-01],
       [3.47142369e-01],
       [1.53735146e-01],
       [3.69467020e-01],
       [2.84301281e-01],
       [3.62530142e-01],
       [2.08126158e-01],
       [7.68319428e-01],
       [1.17665857e-01],
       [6.01537645e-01],
       [5.14420390e-01],
       [6.01801693e-01],
       [1.26142189e-01],
       [6.05131239e-02],
       [1.12255506e-01],
       [1.09655671e-01],
       [6.16714120e-01],
       [7.54503310e-02],
       [1.78982504e-02],
       [5.51930308e-01],
       [4.88419801e-01],
       [5.02229869e-01],
       [5.31605422e-01],
       [4.78045195e-02],
       [7.64132023e-01],


In [42]:
# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded)

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,

In [61]:
results = np.argmax(rounded,axis = 0)
results = pd.Series(rounded)

In [62]:
submission = pd.concat([pd.Series(range(1,769)),results],axis = 1)

In [63]:
submission[0] = submission[0].astype('int32')

In [64]:
submission

0    1
0      1  1.0
1      2  0.0
2      3  1.0
3      4  0.0
4      5  1.0
5      6  0.0
6      7  0.0
7      8  0.0
8      9  1.0
9     10  0.0
10    11  0.0
11    12  1.0
12    13  0.0
13    14  1.0
14    15  1.0
15    16  0.0
16    17  0.0
17    18  0.0
18    19  0.0
19    20  0.0
20    21  0.0
21    22  0.0
22    23  1.0
23    24  0.0
24    25  1.0
25    26  1.0
26    27  1.0
27    28  0.0
28    29  0.0
29    30  0.0
..   ...  ...
738  739  0.0
739  740  0.0
740  741  1.0
741  742  0.0
742  743  0.0
743  744  0.0
744  745  1.0
745  746  0.0
746  747  0.0
747  748  0.0
748  749  1.0
749  750  0.0
750  751  0.0
751  752  0.0
752  753  0.0
753  754  1.0
754  755  1.0
755  756  0.0
756  757  0.0
757  758  0.0
758  759  0.0
759  760  1.0
760  761  0.0
761  762  1.0
762  763  0.0
763  764  1.0
764  765  0.0
765  766  0.0
766  767  0.0
767  768  0.0

[768 rows x 2 columns]